Fix test
The tests no longer run:

	$ go test ./...
	zero/bool_test.go:176: Errorf format %d has arg b.Bool of wrong type bool

This is because go test now automatically runs go vet.